: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX conc_ca
    USEION ca READ ica WRITE cai
    RANGE tau, gamma, inf
    THREADSAFE
}

PARAMETER {
    gamma = 0.0259106803503
    tau = 80.0 (ms)
    inf = 0.0001 (mM)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
}

STATE {
    cai (mM)
}

BREAKPOINT {
    SOLVE states METHOD cnexp
}

INITIAL {
    cai = inf
}

DERIVATIVE states {
    cai' = - gamma * ica - (cai - inf) / tau
}

