#!/usr/bin/env python3
import os, subprocess

# move to home directory so that we don't call compilechannels from the package
# root directory
os.chdir(os.path.expanduser("~"))
subprocess.call(['compilechannels', 'default'])