: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ICa_HVA
    USEION ca WRITE ica
    RANGE  g, e
    GLOBAL h_inf, m_inf, tau_h, tau_m
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = 50.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
    h_inf      
    tau_h (ms) 
    m_inf      
    tau_m (ms) 
    v (mV)
    temp (degC)
}

STATE {
    h
    m
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ica = g * (h*pow(m, 2)) * (v - e)
}

INITIAL {
    rates(v)
    h = h_inf
    m = m_inf
}

DERIVATIVE states {
    rates(v)
    h' = (h_inf - h) /  tau_h 
    m' = (m_inf - m) /  tau_m 
}

PROCEDURE rates(v) {
    temp = celsius
    h_inf = 0.000457*(exp(-1.0/28.0*v - 15.0/28.0) + 1)*exp((1.0/28.0)*v + 15.0/28.0)/((0.0064999999999999997*exp((1.0/50.0)*v + 13.0/50.0) + 0.000457)*exp((1.0/28.0)*v + 15.0/28.0) + 0.000457)
    tau_h = 1.0/(0.000457*exp(-1.0/50.0*v - 13.0/50.0) + 0.0064999999999999997/(exp(-1.0/28.0*v - 15.0/28.0) + 1))
    m_inf = (0.055*v + 1.4850000000000001)*exp(0.32198142414860681*v)/(0.055*(v + 27)*exp(0.32198142414860681*v) + 0.011405722114984784*exp(0.26315789473684209*v) - 9.3615164426375433e-6)
    tau_m = (1.0*exp(0.26315789473684209*v) - 0.0008207736737982094)*exp((1.0/17.0)*v)/(0.055*(v + 27)*exp(0.32198142414860681*v) + 0.011405722114984784*exp(0.26315789473684209*v) - 9.3615164426375433e-6)
}

