: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX Ih
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL hf_inf, hs_inf, tau_hf, tau_hs
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -43.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    hf_inf      
    tau_hf (ms) 
    hs_inf      
    tau_hs (ms) 
    v (mV)
    temp (degC)
}

STATE {
    hf
    hs
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * (0.80000000000000004*hf + 0.20000000000000001*hs) * (v - e)
}

INITIAL {
    rates(v)
    hf = hf_inf
    hs = hs_inf
}

DERIVATIVE states {
    rates(v)
    hf' = (hf_inf - hf) /  tau_hf 
    hs' = (hs_inf - hs) /  tau_hs 
}

PROCEDURE rates(v) {
    temp = celsius
    hf_inf = 1.0/(122306.53009058574*exp(0.14285714285714285*v) + 1.0)
    tau_hf = 40.0
    hs_inf = 1.0/(122306.53009058574*exp(0.14285714285714285*v) + 1.0)
    tau_hs = 300.0
}

