: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX IKv3_1
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL m_inf, tau_m
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -85.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    m_inf      
    tau_m (ms) 
    v (mV)
    temp (degC)
}

STATE {
    m
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * (m) * (v - e)
}

INITIAL {
    rates(v)
    m = m_inf
}

DERIVATIVE states {
    rates(v)
    m' = (m_inf - m) /  tau_m 
}

PROCEDURE rates(v) {
    temp = celsius
    m_inf = 1.0*exp(0.10309278350515465*v)/(1.0*exp(0.10309278350515465*v) + 6.8746109409659972)
    tau_m = 4.0*exp(0.022655188038060714*v)/(1.0*exp(0.022655188038060714*v) + 0.34825317301427267)
}

