: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX IPiecewiseChannel
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL a_inf, b_inf, tau_a, tau_b
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -28.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    a_inf      
    tau_a (ms) 
    b_inf      
    tau_b (ms) 
    v (mV)
    temp (degC)
}

STATE {
    a
    b
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * (a + b) * (v - e)
}

INITIAL {
    rates(v)
    a = a_inf
    b = b_inf
}

DERIVATIVE states {
    rates(v)
    a' = (a_inf - a) /  tau_a 
    b' = (b_inf - b) /  tau_b 
}

PROCEDURE rates(v) {
    temp = celsius
    if (v < -50.0) {
       a_inf = 0.10000000000000001
    }
    else {
       a_inf = 0.90000000000000002
    }
    if (v < -50.0) {
       tau_a = 10.0
    }
    else {
       tau_a = 20.0
    }
    if (v < -50.0) {
       b_inf = 0.80000000000000004
    }
    else {
       b_inf = 0.20000000000000001
    }
    if (v < -50.0) {
       tau_b = 0.10000000000000001
    }
    else {
       tau_b = 50.0
    }
}

