: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ISK
    USEION k WRITE ik
    USEION ca READ cai
    RANGE  g, e
    GLOBAL z_inf, tau_z
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -85.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    z_inf      
    tau_z (ms) 
    cai (mM)
    v (mV)
    temp (degC)
}

STATE {
    z
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * (z) * (v - e)
}

INITIAL {
    rates(v, cai)
    z = z_inf
}

DERIVATIVE states {
    rates(v, cai)
    z' = (z_inf - z) /  tau_z 
}

PROCEDURE rates(v, cai) {
    temp = celsius
    z_inf = 1.0/(6.9286494134258575e-17*pow(1.0/cai, 4.7999999999999998) + 1.0)
    tau_z = 1.0
}

