: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ISKv3_1
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL z_inf, tau_z
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -85.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    z_inf      
    tau_z (ms) 
    v (mV)
    temp (degC)
}

STATE {
    z
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * (z) * (v - e)
}

INITIAL {
    rates(v)
    z = z_inf
}

DERIVATIVE states {
    rates(v)
    z' = (z_inf - z) /  tau_z 
}

PROCEDURE rates(v) {
    temp = celsius
    z_inf = exp(0.10309278350515465*v)/(exp(0.10309278350515465*v) + 6.8746109409659972)
    tau_z = 4.0*exp(0.022655188038060714*v)/(exp(0.022655188038060714*v) + 0.34825317301427267)
}

