: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ITestChannel
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL a00_inf, a01_inf, a02_inf, a10_inf, a11_inf, a12_inf, tau_a00, tau_a01, tau_a02, tau_a10, tau_a11, tau_a12
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -23.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    a00_inf      
    tau_a00 (ms) 
    a01_inf      
    tau_a01 (ms) 
    a02_inf      
    tau_a02 (ms) 
    a10_inf      
    tau_a10 (ms) 
    a11_inf      
    tau_a11 (ms) 
    a12_inf      
    tau_a12 (ms) 
    v (mV)
    temp (degC)
}

STATE {
    a00
    a01
    a02
    a10
    a11
    a12
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * (5*pow(a00, 3)*pow(a01, 3)*a02 + pow(a10, 2)*pow(a11, 2)*a12) * (v - e)
}

INITIAL {
    rates(v)
    a00 = a00_inf
    a01 = a01_inf
    a02 = a02_inf
    a10 = a10_inf
    a11 = a11_inf
    a12 = a12_inf
}

DERIVATIVE states {
    rates(v)
    a00' = (a00_inf - a00) /  tau_a00 
    a01' = (a01_inf - a01) /  tau_a01 
    a02' = (a02_inf - a02) /  tau_a02 
    a10' = (a10_inf - a10) /  tau_a10 
    a11' = (a11_inf - a11) /  tau_a11 
    a12' = (a12_inf - a12) /  tau_a12 
}

PROCEDURE rates(v) {
    temp = celsius
    a00_inf = 1.0/(0.74081822068171788*exp(0.01*v) + 1.0)
    tau_a00 = 1.0
    a01_inf = 1.0*exp(0.01*v)/(1.0*exp(0.01*v) + 1.3498588075760032)
    tau_a01 = 2.0
    a02_inf = -10.0
    tau_a02 = 1.0
    a10_inf = 2.0/(0.74081822068171788*exp(0.01*v) + 1.0)
    tau_a10 = 2.0
    a11_inf = 2.0*exp(0.01*v)/(1.0*exp(0.01*v) + 1.3498588075760032)
    tau_a11 = 2.0
    a12_inf = -30.0
    tau_a12 = 3.0
}

