: This mod file is automaticaly generated by the ``neat.channels.ionchannels`` module

NEURON {
    SUFFIX ITestChannel2
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL a00_inf, a01_inf, a10_inf, a11_inf, tau_a00, tau_a01, tau_a10, tau_a11
    THREADSAFE
}

PARAMETER {
    g = 0.0 (S/cm2)
    e = -23.0 (mV)
    celsius (degC)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    a00_inf      
    tau_a00 (ms) 
    a01_inf      
    tau_a01 (ms) 
    a10_inf      
    tau_a10 (ms) 
    a11_inf      
    tau_a11 (ms) 
    v (mV)
    temp (degC)
}

STATE {
    a00
    a01
    a10
    a11
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * (0.90000000000000002*pow(a00, 3)*pow(a01, 2) + 0.10000000000000001*pow(a10, 2)*a11) * (v - e)
}

INITIAL {
    rates(v)
    a00 = a00_inf
    a01 = a01_inf
    a10 = a10_inf
    a11 = a11_inf
}

DERIVATIVE states {
    rates(v)
    a00' = (a00_inf - a00) /  tau_a00 
    a01' = (a01_inf - a01) /  tau_a01 
    a10' = (a10_inf - a10) /  tau_a10 
    a11' = (a11_inf - a11) /  tau_a11 
}

PROCEDURE rates(v) {
    temp = celsius
    a00_inf = 0.29999999999999999
    tau_a00 = 1.0
    a01_inf = 0.5
    tau_a01 = 2.0
    a10_inf = 0.40000000000000002
    tau_a10 = 2.0
    a11_inf = 0.59999999999999998
    tau_a11 = 2.0
}

